version: '3.8'

services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"  # Main LocalStack gateway
    environment:
      - SERVICES=s3
      - DEBUG=1
    volumes:
      - localstack_data:/var/lib/localstack

  cassandra:
    image: cassandra:4.0
    container_name: cassandra
    ports:
      - "9042:9042"  # CQL Port
    environment:
      - CASSANDRA_CLUSTER_NAME=DataLakeCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
    volumes:
      - cassandra_data:/var/lib/cassandra

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: curated
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql

  airflow:
    image: apache/airflow:2.7.0
    container_name: airflow
    ports:
      - "8080:8080"  # Airflow webserver
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////usr/local/airflow/airflow.db
    volumes:
      - ./dags:/opt/airflow/dags  # DAGs still need to be in your project folder
      - ./logs:/opt/airflow/logs  # Logs for easier access during debugging
    command: ["webserver"]

volumes:
  localstack_data:
  cassandra_data:
  mysql_data:
