version: '3.8'

services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
    volumes:
      - localstack_data:/var/lib/localstack

  cassandra:
    image: cassandra:4.0
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=DataLakeCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
    volumes:
      - cassandra_data:/var/lib/cassandra

  postgresql:
    image: timescale/timescaledb:latest-pg15
    container_name: postgresql
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  airflow-db:
    image: postgres:15
    container_name: airflow-db
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - airflow_db_data:/var/lib/postgresql/data

  airflow-init:
    image: apache/airflow:2.7.0
    depends_on:
      - airflow-db
      - redis
    env_file:
      - .env
    entrypoint: ["/bin/bash", "-c", "airflow db init && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com"]

  airflow-webserver:
    image: apache/airflow:2.7.0
    depends_on:
      - airflow-init
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./src:/opt/airflow/src  # Monte le dossier local src/ dans le conteneur
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.7.0
    depends_on:
      - airflow-webserver
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./src:/opt/airflow/src  # Monte le dossier local src/ dans le conteneur
    command: scheduler

volumes:
  localstack_data:
  cassandra_data:
  postgresql_data:
  airflow_db_data:
