version: '3.8'

services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"  # Main LocalStack gateway
    environment:
      - SERVICES=s3
      - DEBUG=1
    volumes:
      - localstack_data:/var/lib/localstack
    # restart: "no"

  cassandra:
    image: cassandra:4.0
    container_name: cassandra
    ports:
      - "9042:9042"  # CQL Port
    environment:
      - CASSANDRA_CLUSTER_NAME=DataLakeCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
    volumes:
      - cassandra_data:/var/lib/cassandra
    # restart: "no"

  postgresql:
    image: timescale/timescaledb:latest-pg15
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: curated
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    # restart: "no"

  airflow:
    image: apache/airflow:2.7.0
    container_name: airflow
    ports:
      - "8080:8080"  # Airflow webserver
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////usr/local/airflow/airflow.db
    volumes:
      - ./dags:/opt/airflow/dags  # DAGs still need to be in your project folder
      - ./logs:/opt/airflow/logs  # Logs for easier access during debugging
    command: ["webserver"]
    # restart: "no"

volumes:
  localstack_data:
  cassandra_data:
  postgresql_data:
