# See report or go to https://www.geodair.fr/sites/default/files/media-files/2022-05/liste_polluants.pdf 
- code: "01" 
  short_name: "SO2"
  full_name: "dioxyde de soufre"
  unit: "µg-m3"
- code: "03"
  short_name: "NO2"
  full_name: "dioxyde d'azote"
  unit: "µg-m3"
# - code: "04"
#   short_name: "CO"
#   full_name: "monoxyde de carbone"
#   unit: "mg-m3"
# - code: "08"
#   short_name: "O3"
#   full_name: "ozone"
#   unit: "µg-m3"
# - code: "12"
#   short_name: "NOX"
#   full_name: "oxydes d'azote"
#   unit: "µg-m3"
# - code: "19"
#   short_name: "Pb dans les PM10"
#   full_name: "plomb dans les PM10"
#   unit: "µg-m3"
# - code: "24"
#   short_name: "PM10"
#   full_name: "particules de diamètre inférieur à 10 µm"
#   unit: "µg-m3"
# - code: "39"
#   short_name: "PM2.5"
#   full_name: "particules de diamètre inférieur à 2,5 µm"
#   unit: "µg-m3"
# - code: "80"
#   short_name: "As dans les PM10"
#   full_name: "arsenic dans les PM10"
#   unit: "ng-m3"
# - code: "82"
#   short_name: "Cd dans les PM10"
#   full_name: "cadmium dans les PM10"
#   unit: "ng-m3"
# - code: "87"
#   short_name: "Ni dans les PM10"
#   full_name: "nickel dans les PM10"
#   unit: "ng-m3"
# - code: "P6"
#   short_name: "BaP dans les PM10"
#   full_name: "benzo[a]pyrène dans les PM10"
#   unit: "ng-m3"
# - code: "V4"
#   short_name: "C6H6"
#   full_name: "benzène"
#   unit: "µg-m3"
